<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Pivota</title>

    <!-- css -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/login.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.css') ?>

</head>

<body class="md-skin fixed-nav">

    <div class="col-lg-12">
        <?php echo $this->content; ?>
    </div>

    <!-- Mainly scripts -->
    <script src="<?php echo($this->basePath() . '/'); ?>js/jquery-2.1.1.js"></script>
    <script src="<?php echo($this->basePath() . '/'); ?>js/bootstrap.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="<?php echo($this->basePath() . '/'); ?>js/inspinia.js"></script>
    <script src="js/plugins/iCheck/icheck.min.js"></script>

</body>

</html>
