<?php
// In any of your .phtml files:
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

$form = $this->form;
$form->prepareElements();
?>

<div class="middle-box text-center loginscreen animated fadeInDown">
    <div>
        <div>

            <h1 id="login-h1">Pivota</h1>

        </div>

        <?php
        echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
        ?>
        <h3>Bem vindo</h3>
        <p>Faça login ou cadastre-se!</p>
        <?php echo $this->form()->openTag($form); ?>
            <div class="form-group">
                <input name="username" type="text" class="form-control" placeholder="nome de usuário" required="">
            </div>
            <div class="form-group">
                <input name="password" type="password" class="form-control" placeholder="senha" required="">
            </div>
            <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

            <a href="#">
                <small>Esqueceu a senha?</small>
            </a>

            <p class="text-muted text-center">
                <small>Não tem uma conta?</small>
            </p>
            <a class="btn btn-sm btn-white btn-block" href="/cadastro">Criar uma conta</a>
        </form>
        <p class="m-t">
            <small>Pivota &copy; 2016</small>
        </p>
    </div>
</div>

